name: iot-manager webapp

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master

    - name: Gastby Publish
      uses: enriikke/gatsby-gh-pages-action@2.1.1
      with:
        access-token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        deploy-branch: gh-pages
        gatsby-args: --prefix-paths
